-- Script completo para criar tabela de categorias profissionais com grupos e graus

-- 1. Criar a tabela (se não existir)
CREATE TABLE IF NOT EXISTS categorias_profissionais (
  cbo VARCHAR(10) PRIMARY KEY,
  categoria VARCHAR(255) NOT NULL,
  grupo VARCHAR(50),
  grau_instrucao VARCHAR(50),
  cpf_operador VARCHAR(20),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Inserir dados iniciais (ordenados alfabeticamente por grupo e depois por categoria)
INSERT INTO categorias_profissionais (cbo, categoria, grupo, grau_instrucao) VALUES
-- ADMINISTRATIVO
('2011', 'ADMINISTRADOR', 'ADMINISTRATIVO', 'SUPERIOR'),
('2012', 'ANALISTA ADMINISTRATIVO', 'ADMINISTRATIVO', 'SUPERIOR'),
('2013', 'ASSISTENTE ADMINISTRATIVO', 'ADMINISTRATIVO', 'MÉDIO'),

-- ENFERMAGEM
('2235', 'ENFERMEIRO', 'ENFERMAGEM', 'SUPERIOR'),
('2236', 'ENFERMEIRO OBSTETRA', 'ENFERMAGEM', 'SUPERIOR'),
('2237', 'ENFERMEIRO SANITARISTA', 'ENFERMAGEM', 'SUPERIOR'),
('3211', 'TÉCNICO DE ENFERMAGEM', 'ENFERMAGEM', 'TÉCNICO'),
('3221', 'AUXILIAR DE ENFERMAGEM', 'ENFERMAGEM', 'TÉCNICO'),

-- MÉDICO
('2231', 'RESIDENTE MÉDICO', 'MEDICO', 'SUPERIOR'),
('2251', 'MÉDICO CLÍNICO', 'MEDICO', 'SUPERIOR'),
('2252', 'MÉDICO GINECOLOGISTA OBSTETRA', 'MEDICO', 'SUPERIOR'),
('2253', 'MÉDICO PEDIATRA', 'MEDICO', 'SUPERIOR'),
('2254', 'MÉDICO PSIQUIATRA', 'MEDICO', 'SUPERIOR'),
('2255', 'MÉDICO CARDIOLOGISTA', 'MEDICO', 'SUPERIOR'),
('2256', 'MÉDICO DERMATOLOGISTA', 'MEDICO', 'SUPERIOR'),
('2257', 'MÉDICO ENDOCRINOLOGISTA', 'MEDICO', 'SUPERIOR'),
('2258', 'MÉDICO GASTROENTEROLOGISTA', 'MEDICO', 'SUPERIOR'),
('2259', 'MÉDICO NEUROLOGISTA', 'MEDICO', 'SUPERIOR'),
('2260', 'MÉDICO OFTALMOLOGISTA', 'MEDICO', 'SUPERIOR'),
('2261', 'MÉDICO ORTOPEDISTA', 'MEDICO', 'SUPERIOR'),
('2262', 'MÉDICO OTORRINOLARINGOLOGISTA', 'MEDICO', 'SUPERIOR'),
('2263', 'MÉDICO UROLOGISTA', 'MEDICO', 'SUPERIOR'),
('2264', 'MÉDICO RADIOLOGISTA', 'MEDICO', 'SUPERIOR'),
('2265', 'MÉDICO PATOLOGISTA', 'MEDICO', 'SUPERIOR'),
('2266', 'MÉDICO ANESTESISTA', 'MEDICO', 'SUPERIOR'),
('2267', 'MÉDICO CIRURGIÃO GERAL', 'MEDICO', 'SUPERIOR'),
('2268', 'MÉDICO CIRURGIÃO PEDIÁTRICO', 'MEDICO', 'SUPERIOR'),
('2269', 'MÉDICO NEONATOLOGISTA', 'MEDICO', 'SUPERIOR'),

-- OUTROS DE NÍVEL SUPERIOR
('2232', 'ODONTÓLOGO', 'OUTROS DE NIVEL SUPERIOR', 'SUPERIOR'),
('2233', 'FARMACÊUTICO', 'OUTROS DE NIVEL SUPERIOR', 'SUPERIOR'),
('2234', 'FISIOTERAPEUTA', 'OUTROS DE NIVEL SUPERIOR', 'SUPERIOR'),
('2237', 'NUTRICIONISTA', 'OUTROS DE NIVEL SUPERIOR', 'SUPERIOR'),
('2238', 'PSICÓLOGO', 'OUTROS DE NIVEL SUPERIOR', 'SUPERIOR'),
('2239', 'ASSISTENTE SOCIAL', 'OUTROS DE NIVEL SUPERIOR', 'SUPERIOR'),
('2240', 'TERAPEUTA OCUPACIONAL', 'OUTROS DE NIVEL SUPERIOR', 'SUPERIOR'),
('2241', 'FONOAUDIÓLOGO', 'OUTROS DE NIVEL SUPERIOR', 'SUPERIOR'),

-- SAÚDE BUCAL
('3222', 'AUXILIAR DE SAÚDE BUCAL', 'SAUDE BUCAL', 'TÉCNICO'),
('3223', 'TÉCNICO EM SAÚDE BUCAL', 'SAUDE BUCAL', 'TÉCNICO'),
('2232', 'CIRURGIÃO DENTISTA', 'SAUDE BUCAL', 'SUPERIOR'),

-- TACS/ACS
('515105', 'AGENTE COMUNITÁRIO DE SAÚDE', 'TACS/ACS', 'MÉDIO'),
('3212', 'AGENTE DE SAÚDE PÚBLICA', 'TACS/ACS', 'MÉDIO'),
('3213', 'VISITADOR SANITÁRIO', 'TACS/ACS', 'MÉDIO'),
('3214', 'AUXILIAR DE SAÚDE PÚBLICA', 'TACS/ACS', 'MÉDIO')
ON CONFLICT (cbo) DO NOTHING;